In [91]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


__1. Import the numpy package under the name `np`__

In [92]:
import numpy as np

__2. Print the numpy version and the configuration__

In [93]:
print(np.__version__)
print(np.__builtins__)

1.26.4
{'__name__': 'builtins', '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but can be useful in modules that provide\nobjects with the same name as a built-in value, but in\nwhich the built-in of that name is also needed.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <bui

__3. Create a null vector of size 10__

In [94]:
null_arr = np.zeros(10, dtype=np.int32)

In [95]:
print(null_arr)

[0 0 0 0 0 0 0 0 0 0]


__4. How to find the memory size of any array__

In [96]:
print(null_arr.nbytes)

40


__Question 5__

In [97]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

__Question 6__

In [98]:
Z = np.zeros(10, dtype=np.int64)
Z[4] = 1

In [99]:
Z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

__Question 7__

In [100]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [101]:
arr = np.arange(start=10,stop=50, step=1, dtype=np.int64)

In [102]:
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


__Question 8__

In [103]:
X = np.array([1, 2, 3, 4, 5])

In [104]:
X

array([1, 2, 3, 4, 5])

In [105]:
reversed_X = X[::-1]

In [106]:
reversed_X

array([5, 4, 3, 2, 1])

__Question 9__

In [107]:
X = np.arange(9).reshape(3, 3)

In [108]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

__Question 10__

In [109]:
X = [1, 2, 0, 0, 4, 0]

In [110]:
Y = np.nonzero(X)

In [111]:
Y

(array([0, 1, 4], dtype=int64),)

__Question 11__

In [112]:
X = np.eye(3)

In [113]:
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

__Question 12__

In [114]:
X = np.random.random((3, 3, 3))

In [115]:
X

array([[[0.76030702, 0.42994973, 0.47068033],
        [0.62452418, 0.24982515, 0.64908746],
        [0.80796748, 0.45329751, 0.36976263]],

       [[0.45113062, 0.01732164, 0.17925535],
        [0.28227831, 0.82436742, 0.28625438],
        [0.96660187, 0.48459386, 0.03565581]],

       [[0.63809533, 0.59992399, 0.11231697],
        [0.64297314, 0.63509556, 0.11316278],
        [0.47494909, 0.25700497, 0.00398458]]])

__Question 13__

In [116]:
X = np.random.random((10, 10))

X

array([[0.11396369, 0.55545263, 0.93045628, 0.81291986, 0.31947089,
        0.37311777, 0.65463113, 0.1343912 , 0.55346619, 0.28945859],
       [0.17782352, 0.34147084, 0.54383032, 0.34498129, 0.29833477,
        0.59470615, 0.96681444, 0.22981404, 0.39740069, 0.05312547],
       [0.5826015 , 0.25564784, 0.52552329, 0.59351221, 0.00132828,
        0.35738225, 0.76583985, 0.95772079, 0.72592001, 0.17601804],
       [0.71436049, 0.42199093, 0.60453301, 0.0104046 , 0.73898121,
        0.13453968, 0.37598389, 0.81317838, 0.42718165, 0.65456429],
       [0.01392289, 0.23643999, 0.70363579, 0.32229602, 0.8817684 ,
        0.02487538, 0.42463948, 0.22848462, 0.23614334, 0.23193239],
       [0.94001206, 0.57508625, 0.993161  , 0.30369618, 0.58922255,
        0.80434427, 0.84065664, 0.36703937, 0.17209794, 0.43058808],
       [0.74065241, 0.86539789, 0.6810495 , 0.26444139, 0.04773895,
        0.19881221, 0.25345813, 0.72215918, 0.2892616 , 0.73199427],
       [0.33644725, 0.24328517, 0.3922769

In [117]:
min_value, max_value = X.min(), X.max()

In [118]:
min_value, max_value

(0.001328278669963212, 0.9931609966730961)

__Question 14__

In [119]:
X= np.random.random(30)

In [120]:
X

array([0.49089561, 0.3952616 , 0.07728331, 0.08169656, 0.92921501,
       0.51985255, 0.21542571, 0.93725635, 0.16183002, 0.57456567,
       0.50029086, 0.80032009, 0.47789021, 0.02674712, 0.7758427 ,
       0.03767586, 0.15186553, 0.98299964, 0.63017689, 0.13381199,
       0.62706968, 0.14769562, 0.8416089 , 0.30584258, 0.15854218,
       0.12844052, 0.94657723, 0.47739436, 0.36073264, 0.03837618])

In [121]:
X.mean()

0.4311061054465354

__Question 15__

In [122]:
X = np.ones((5, 5))

In [123]:
X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [124]:
X[1:-1, 1:-1] = 0

In [125]:
X

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

__Question 16__

In [126]:
X = np.ones((5, 5))

X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [127]:
X = np.pad(X, constant_values=0, mode='constant', pad_width=1)

X

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [128]:
X = np.ones((5, 5))

X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [129]:
X[:, [0, -1]] = 0
X[[0, -1], :] = 0

In [130]:
X

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

__Question 17__

In [131]:
print(np.nan)

nan


In [132]:
print(np.inf)

inf


In [133]:
print(0*np.nan)

nan


In [134]:
print(0*np.inf)

nan


In [135]:
print(np.nan == np.nan)

False


In [136]:
print(np.inf > np.nan)

False


In [137]:
print(np.nan - np.nan)

nan


In [138]:
print(np.nan in set([np.nan]))

True


__Question 18__

In [139]:
X = np.diag(1+np.arange(4), k=-1)

In [140]:
X

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

__Question 19__

In [141]:
X = np.zeros((8, 8), dtype=int)
X[1::2, ::2] = 1
X[::2, 1::2] = 1

In [142]:
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

__Question 20__

In [143]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


__Question 21__

In [144]:
X = np.tile( np.array([[0,1],[1,0]]), (4,4))

In [145]:
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

__Question 22__

In [146]:
Z = np.random.random((5, 5))
Z = (Z - np.mean(Z)) / (np.std(Z))

In [147]:
Z

array([[-1.30537884,  0.3126601 , -0.20512764,  0.16305433,  1.46475089],
       [-0.37632576, -0.70149886, -0.19716806, -1.65628419,  1.51143683],
       [ 0.93330962,  0.84079172,  1.1295419 ,  0.37866532, -1.02652286],
       [-0.00167062, -1.42139931,  1.44311581,  0.49911683,  0.66442182],
       [-1.4845921 , -1.1822418 ,  1.13272019, -1.21117935,  0.29580402]])

__Question 23__

In [148]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [149]:
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [150]:
pixel = np.array((255, 0, 0, 255), dtype=color)

In [151]:
print(pixel)

(255, 0, 0, 255)


__Question 24__

In [152]:
X = np.arange(15).reshape(5, 3)
Y = np.arange(6).reshape(3, 2)

In [153]:
np.dot(X, Y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [154]:
X @ Y

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

__Question 25__

In [155]:
X = np.arange(15)
X[(3 < X) & (X < 8)] *= -1
X

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])