In [2]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


__1. Import the numpy package under the name `np`__

In [3]:
import numpy as np

__2. Print the numpy version and the configuration__

In [4]:
print(np.__version__)
print(np.__builtins__)

1.26.4
{'__name__': 'builtins', '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but can be useful in modules that provide\nobjects with the same name as a built-in value, but in\nwhich the built-in of that name is also needed.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <bui

__3. Create a null vector of size 10__

In [5]:
null_arr = np.zeros(10, dtype=np.int32)

In [6]:
print(null_arr)

[0 0 0 0 0 0 0 0 0 0]


__4. How to find the memory size of any array__

In [7]:
print(null_arr.nbytes)

40


__Question 5__

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

__Question 6__

In [9]:
Z = np.zeros(10, dtype=np.int64)
Z[4] = 1

In [10]:
Z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

__Question 7__

In [11]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [12]:
arr = np.arange(start=10,stop=50, step=1, dtype=np.int64)

In [13]:
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


__Question 8__

In [14]:
X = np.array([1, 2, 3, 4, 5])

In [15]:
X

array([1, 2, 3, 4, 5])

In [16]:
reversed_X = X[::-1]

In [17]:
reversed_X

array([5, 4, 3, 2, 1])

__Question 9__

In [18]:
X = np.arange(9).reshape(3, 3)

In [19]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

__Question 10__

In [20]:
X = [1, 2, 0, 0, 4, 0]

In [21]:
Y = np.nonzero(X)

In [22]:
Y

(array([0, 1, 4], dtype=int64),)

__Question 11__

In [23]:
X = np.eye(3)

In [24]:
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

__Question 12__

In [25]:
X = np.random.random((3, 3, 3))

In [26]:
X

array([[[0.40432148, 0.63647323, 0.50968496],
        [0.65519438, 0.68535235, 0.43323805],
        [0.57884807, 0.97306962, 0.10564368]],

       [[0.77714668, 0.89858975, 0.5980579 ],
        [0.02123929, 0.06134659, 0.77518565],
        [0.03171249, 0.15462215, 0.62682782]],

       [[0.96942575, 0.11909361, 0.5637781 ],
        [0.66107751, 0.33747611, 0.95384341],
        [0.74125975, 0.05163873, 0.96790078]]])

__Question 13__

In [27]:
X = np.random.random((10, 10))

X

array([[0.10929375, 0.57332526, 0.33480797, 0.5468391 , 0.2525543 ,
        0.78487666, 0.04568754, 0.93316532, 0.28335109, 0.97063904],
       [0.66980075, 0.46202376, 0.27472572, 0.52102789, 0.44331133,
        0.38393293, 0.42937229, 0.28208335, 0.39511163, 0.18376374],
       [0.54182355, 0.99630727, 0.65578981, 0.68121639, 0.24705221,
        0.6492239 , 0.50227481, 0.33635045, 0.4852496 , 0.38642614],
       [0.79633275, 0.69488096, 0.57108528, 0.92662361, 0.93357907,
        0.40782174, 0.50311436, 0.10036121, 0.467066  , 0.80613023],
       [0.9392169 , 0.31544743, 0.43275336, 0.96934168, 0.27652701,
        0.47330221, 0.28580702, 0.31074173, 0.42687075, 0.41522091],
       [0.67238293, 0.60674224, 0.65768753, 0.66684548, 0.15133387,
        0.69212387, 0.67056535, 0.22973093, 0.84523725, 0.80798198],
       [0.71076162, 0.09858325, 0.69503957, 0.60790532, 0.56733261,
        0.8020926 , 0.00750222, 0.38486295, 0.112117  , 0.55324092],
       [0.62416729, 0.25690006, 0.4365124

In [28]:
min_value, max_value = X.min(), X.max()

In [29]:
min_value, max_value

(0.004120706789023432, 0.9963072694283649)

__Question 14__

In [30]:
X= np.random.random(30)

In [31]:
X

array([0.99944912, 0.35760975, 0.32787527, 0.49061867, 0.83707661,
       0.25592646, 0.7514686 , 0.4148611 , 0.07694486, 0.13307568,
       0.05872499, 0.95415086, 0.16727336, 0.21599487, 0.69519006,
       0.24947444, 0.7118143 , 0.79054871, 0.37570244, 0.02481275,
       0.20861608, 0.41787811, 0.93781816, 0.25704116, 0.69799837,
       0.63672397, 0.1043809 , 0.01753827, 0.49678915, 0.6690894 ])

In [32]:
X.mean()

0.4444155489985627

__Question 15__

In [33]:
X = np.ones((5, 5))

In [34]:
X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
X[1:-1, 1:-1] = 0

In [36]:
X

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

__Question 16__

In [37]:
X = np.ones((5, 5))

X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [38]:
X = np.pad(X, constant_values=0, mode='constant', pad_width=1)

X

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [39]:
X = np.ones((5, 5))

X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
X[:, [0, -1]] = 0
X[[0, -1], :] = 0

In [41]:
X

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

__Question 17__

In [42]:
print(np.nan)

nan


In [43]:
print(np.inf)

inf


In [44]:
print(0*np.nan)

nan


In [45]:
print(0*np.inf)

nan


In [46]:
print(np.nan == np.nan)

False


In [47]:
print(np.inf > np.nan)

False


In [48]:
print(np.nan - np.nan)

nan


In [49]:
print(np.nan in set([np.nan]))

True


__Question 18__

In [50]:
X = np.diag(1+np.arange(4), k=-1)

In [51]:
X

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

__Question 19__

In [53]:
X = np.zeros((8, 8), dtype=int)
X[1::2, ::2] = 1
X[::2, 1::2] = 1

In [54]:
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

__Question 20__

In [57]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)
