__Import the dependencies__

In [1]:
import numpy as np

In [3]:
# Create array with 10 zeros
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
X = np.ones(10)
print(X)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [6]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [7]:
np.arange(start=10, stop=51, step=1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [8]:
np.arange(9).reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.info(np.random.rand)

rand(d0, d1, ..., dn)

Random values in a given shape.

.. note::
    This is a convenience function for users porting code from Matlab,
    and wraps `random_sample`. That function takes a
    tuple to specify the size of the output, which is consistent with
    other NumPy functions like `numpy.zeros` and `numpy.ones`.

Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

Parameters
----------
d0, d1, ..., dn : int, optional
    The dimensions of the returned array, must be non-negative.
    If no argument is given a single Python float is returned.

Returns
-------
out : ndarray, shape ``(d0, d1, ..., dn)``
    Random values.

See Also
--------
random

Examples
--------
>>> np.random.rand(3,2)
array([[ 0.14022471,  0.96360618],  #random
       [ 0.37601032,  0.25528411],  #random
       [ 0.49313049,  0.94909878]]) #random


In [14]:
np.random.rand(1)

array([0.37539])

In [17]:
np.random.randn(25)

array([-0.62479592, -0.61883448, -0.20673223,  0.36471649,  1.25972199,
        1.36024302,  0.35554685,  0.68569745, -0.41075116, -0.64148007,
        0.27135493, -0.65810709, -0.6579831 , -0.16141835, -0.24981089,
       -0.48088656, -0.57630824,  0.64790896, -0.03312129,  0.39068509,
       -0.07804737,  0.30979514, -0.46150708, -1.17874137,  0.48659772])

In [18]:
np.arange(0.01,1.01,0.01).reshape([10,10])

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [19]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [22]:
mat = np.arange(1, 26).reshape(5, 5)

In [23]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [25]:
mat[::2, 1::2]

array([[ 2,  4],
       [12, 14],
       [22, 24]])

In [26]:
mat[1::2, ::2]

array([[ 6,  8, 10],
       [16, 18, 20]])

In [27]:
mat.sum()

325

In [28]:
np.std(mat)

7.211102550927978

In [29]:
(mat - np.mean(mat))/np.std(mat)

array([[-1.66410059, -1.52542554, -1.38675049, -1.24807544, -1.10940039],
       [-0.97072534, -0.83205029, -0.69337525, -0.5547002 , -0.41602515],
       [-0.2773501 , -0.13867505,  0.        ,  0.13867505,  0.2773501 ],
       [ 0.41602515,  0.5547002 ,  0.69337525,  0.83205029,  0.97072534],
       [ 1.10940039,  1.24807544,  1.38675049,  1.52542554,  1.66410059]])

In [30]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])

In [31]:
np.sum(mat, axis=1)

array([ 15,  40,  65,  90, 115])

In [33]:
np.arange(8).reshape(2, 4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])