In [2]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


__1. Import the numpy package under the name `np`__

In [3]:
import numpy as np

__2. Print the numpy version and the configuration__

In [4]:
print(np.__version__)
print(np.__builtins__)

1.26.4
{'__name__': 'builtins', '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but can be useful in modules that provide\nobjects with the same name as a built-in value, but in\nwhich the built-in of that name is also needed.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <bui

__3. Create a null vector of size 10__

In [5]:
null_arr = np.zeros(10, dtype=np.int32)

In [6]:
print(null_arr)

[0 0 0 0 0 0 0 0 0 0]


__4. How to find the memory size of any array__

In [7]:
print(null_arr.nbytes)

40


__Question 5__

In [8]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

__Question 6__

In [9]:
Z = np.zeros(10, dtype=np.int64)
Z[4] = 1

In [10]:
Z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

__Question 7__

In [11]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [12]:
arr = np.arange(start=10,stop=50, step=1, dtype=np.int64)

In [13]:
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


__Question 8__

In [14]:
X = np.array([1, 2, 3, 4, 5])

In [15]:
X

array([1, 2, 3, 4, 5])

In [16]:
reversed_X = X[::-1]

In [17]:
reversed_X

array([5, 4, 3, 2, 1])

__Question 9__

In [18]:
X = np.arange(9).reshape(3, 3)

In [19]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

__Question 10__

In [20]:
X = [1, 2, 0, 0, 4, 0]

In [23]:
Y = np.nonzero(X)

In [24]:
Y

(array([0, 1, 4], dtype=int64),)