In [160]:
!pip install numpy


[notice] A new release of pip is available: 25.1.1 -> 25.2
[notice] To update, run: python.exe -m pip install --upgrade pip


__1. Import the numpy package under the name `np`__

In [161]:
import numpy as np

__2. Print the numpy version and the configuration__

In [162]:
print(np.__version__)
print(np.__builtins__)

1.26.4
{'__name__': 'builtins', '__doc__': "Built-in functions, types, exceptions, and other objects.\n\nThis module provides direct access to all 'built-in'\nidentifiers of Python; for example, builtins.len is\nthe full name for the built-in function len().\n\nThis module is not normally accessed explicitly by most\napplications, but can be useful in modules that provide\nobjects with the same name as a built-in value, but in\nwhich the built-in of that name is also needed.", '__package__': '', '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': ModuleSpec(name='builtins', loader=<class '_frozen_importlib.BuiltinImporter'>, origin='built-in'), '__build_class__': <built-in function __build_class__>, '__import__': <built-in function __import__>, 'abs': <built-in function abs>, 'all': <built-in function all>, 'any': <built-in function any>, 'ascii': <built-in function ascii>, 'bin': <built-in function bin>, 'breakpoint': <built-in function breakpoint>, 'callable': <bui

__3. Create a null vector of size 10__

In [163]:
null_arr = np.zeros(10, dtype=np.int32)

In [164]:
print(null_arr)

[0 0 0 0 0 0 0 0 0 0]


__4. How to find the memory size of any array__

In [165]:
print(null_arr.nbytes)

40


__Question 5__

In [166]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

__Question 6__

In [167]:
Z = np.zeros(10, dtype=np.int64)
Z[4] = 1

In [168]:
Z

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0], dtype=int64)

__Question 7__

In [169]:
np.info(np.arange)

arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interval includes 

In [170]:
arr = np.arange(start=10,stop=50, step=1, dtype=np.int64)

In [171]:
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


__Question 8__

In [172]:
X = np.array([1, 2, 3, 4, 5])

In [173]:
X

array([1, 2, 3, 4, 5])

In [174]:
reversed_X = X[::-1]

In [175]:
reversed_X

array([5, 4, 3, 2, 1])

__Question 9__

In [176]:
X = np.arange(9).reshape(3, 3)

In [177]:
X

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

__Question 10__

In [178]:
X = [1, 2, 0, 0, 4, 0]

In [179]:
Y = np.nonzero(X)

In [180]:
Y

(array([0, 1, 4], dtype=int64),)

__Question 11__

In [181]:
X = np.eye(3)

In [182]:
X

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

__Question 12__

In [183]:
X = np.random.random((3, 3, 3))

In [184]:
X

array([[[0.75022555, 0.86873862, 0.89250938],
        [0.84049153, 0.49244659, 0.32121042],
        [0.77881793, 0.19880849, 0.3336323 ]],

       [[0.16835121, 0.17129773, 0.81800375],
        [0.99335904, 0.10829916, 0.68715183],
        [0.42312806, 0.54249545, 0.4012893 ]],

       [[0.45179148, 0.45482168, 0.67365823],
        [0.08385055, 0.38880832, 0.02198657],
        [0.09544649, 0.45098575, 0.09616007]]])

__Question 13__

In [185]:
X = np.random.random((10, 10))

X

array([[0.53971003, 0.41131626, 0.81965325, 0.32027156, 0.87277276,
        0.08652046, 0.06236221, 0.08108328, 0.72416468, 0.08304802],
       [0.32539603, 0.61599023, 0.71520431, 0.89623654, 0.95294602,
        0.92077392, 0.79382617, 0.25027914, 0.92183483, 0.21141128],
       [0.74437184, 0.10357688, 0.74025695, 0.4445672 , 0.48969628,
        0.2324423 , 0.54876409, 0.81024926, 0.14667192, 0.73063615],
       [0.66447603, 0.17151083, 0.68428677, 0.47854392, 0.9807055 ,
        0.76986301, 0.5069402 , 0.38719549, 0.50250155, 0.38044034],
       [0.7457347 , 0.03567742, 0.26900121, 0.53064927, 0.44003503,
        0.52705908, 0.32076286, 0.0220279 , 0.5130103 , 0.36267283],
       [0.96739135, 0.33527569, 0.52361617, 0.91180718, 0.32576089,
        0.09317262, 0.22242116, 0.82407762, 0.22426056, 0.38910896],
       [0.58058097, 0.03899919, 0.98865964, 0.36062301, 0.97613355,
        0.45162508, 0.44756116, 0.2112352 , 0.24317395, 0.5032375 ],
       [0.54974916, 0.93261341, 0.6367930

In [186]:
min_value, max_value = X.min(), X.max()

In [187]:
min_value, max_value

(0.015958772091434703, 0.9995122862275536)

__Question 14__

In [188]:
X= np.random.random(30)

In [189]:
X

array([0.97903991, 0.15515333, 0.22793235, 0.78311494, 0.6671733 ,
       0.10528275, 0.92094227, 0.07807367, 0.30099567, 0.67246639,
       0.43076045, 0.23249969, 0.42563196, 0.85478891, 0.50881857,
       0.78953575, 0.5745484 , 0.90254318, 0.05164132, 0.97765099,
       0.72773403, 0.11132601, 0.08663321, 0.97145117, 0.05659119,
       0.38830128, 0.71671379, 0.68604559, 0.37445281, 0.70947428])

In [190]:
X.mean()

0.5155772387051925

__Question 15__

In [191]:
X = np.ones((5, 5))

In [192]:
X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [193]:
X[1:-1, 1:-1] = 0

In [194]:
X

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

__Question 16__

In [195]:
X = np.ones((5, 5))

X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [196]:
X = np.pad(X, constant_values=0, mode='constant', pad_width=1)

X

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [197]:
X = np.ones((5, 5))

X

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [198]:
X[:, [0, -1]] = 0
X[[0, -1], :] = 0

In [199]:
X

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

__Question 17__

In [200]:
print(np.nan)

nan


In [201]:
print(np.inf)

inf


In [202]:
print(0*np.nan)

nan


In [203]:
print(0*np.inf)

nan


In [204]:
print(np.nan == np.nan)

False


In [205]:
print(np.inf > np.nan)

False


In [206]:
print(np.nan - np.nan)

nan


In [207]:
print(np.nan in set([np.nan]))

True


__Question 18__

In [208]:
X = np.diag(1+np.arange(4), k=-1)

In [209]:
X

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

__Question 19__

In [210]:
X = np.zeros((8, 8), dtype=int)
X[1::2, ::2] = 1
X[::2, 1::2] = 1

In [211]:
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

__Question 20__

In [212]:
print(np.unravel_index(99, (6,7,8)))

(1, 5, 3)


__Question 21__

In [213]:
X = np.tile( np.array([[0,1],[1,0]]), (4,4))

In [214]:
X

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

__Question 22__

In [215]:
Z = np.random.random((5, 5))
Z = (Z - np.mean(Z)) / (np.std(Z))

In [216]:
Z

array([[ 1.30775382, -1.10500911, -1.46068561,  0.18581283, -0.07776328],
       [-1.00226744,  1.05264075,  1.20402319, -1.31203337, -0.18294805],
       [-0.83733528,  0.24714979,  1.32148176, -0.55198178,  0.32577836],
       [-0.79982131,  0.31727052,  1.38718896, -1.72864965,  1.41436363],
       [ 0.75980427,  0.41075699, -1.54503643,  0.90372031, -0.23421388]])

__Question 23__

In [217]:
color = np.dtype([("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)])

In [218]:
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


In [219]:
pixel = np.array((255, 0, 0, 255), dtype=color)

In [220]:
print(pixel)

(255, 0, 0, 255)


__Question 24__

In [221]:
X = np.arange(15).reshape(5, 3)
Y = np.arange(6).reshape(3, 2)

In [222]:
np.dot(X, Y)

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

In [223]:
X @ Y

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

__Question 25__

In [224]:
X = np.arange(15)
X[(3 < X) & (X < 8)] *= -1
X

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14])

__Question 26__

In [225]:
print(sum(range(5), -1))
from numpy import *
print(sum(range(5), -1))

10
10


__Question 27__

In [226]:
Z**Z

C:\Users\NhanPham\AppData\Local\Temp\ipykernel_17524\2996799114.py:1: RuntimeWarning: invalid value encountered in power
  Z**Z


array([[1.42032366,        nan,        nan, 0.73145041,        nan],
       [       nan, 1.05548733, 1.2505073 ,        nan,        nan],
       [       nan, 0.70789729, 1.44537365,        nan, 0.69393789],
       [       nan, 0.69473367, 1.57459537,        nan, 1.63285686],
       [0.81162734, 0.69386874,        nan, 0.91257186,        nan]])