In [10]:
import numpy as np

In [11]:
exercise_1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
exercise_1[exercise_1 % 2 == 1] = -1

In [13]:
exercise_1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [14]:
exercise_2 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [15]:
exercise_2.reshape(3, 3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
exercise_3 = np.arange(4).reshape(2,-1)

In [19]:
exercise_3 + 202

array([[202, 203],
       [204, 205]])

In [28]:
np.random.randint(30, 41, size=10)

array([37, 40, 33, 30, 32, 33, 33, 38, 38, 37])

In [32]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

np.where(x>y)
# np.where(x==y)

(array([1, 2, 4, 5, 6, 7, 8, 9], dtype=int64),)

In [33]:
exercise_6 = np.arange(100).reshape(5,-1)

In [34]:
exercise_6[:,:4:1]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])